MVCPractice2/Models/BaseEntity.cs
namespace MVCPractice2.Models
{
    public abstract class BaseEntity
    {
        public int Id { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now;
    }
}

MVCPractice2/Models/Setting.cs
namespace MVCPractice2.Models
{
    public class Setting : BaseEntity
    {
        public string? Key { get; set; }
        public string? Value { get; set; }
    }
}

MVCPractice2/Models/Slider.cs
namespace MVCPractice2.Models
{
    public class Slider : BaseEntity
    {
        public string Title { get; set; }
        public string Image { get; set; }
    }
}

MVCPractice2/Models/SliderInfo.cs
namespace MVCPractice2.Models
{
    public class SliderInfo : BaseEntity
    {
        public string Title { get; set; }
        public string Description { get; set; } 
    }
}

MVCPractice2/ViewModels/Slider/SliderInfoUIVM.cs
namespace MVCPractice2.ViewModels.Slider
{
    public class SliderInfoUIVM
    {
        public string Title { get; set; }
        public string Description { get; set; }
    }
}

MVCPractice2/ViewModels/Slider/SliderUIVM.cs
namespace MVCPractice2.ViewModels.Slider
{
    public class SliderUIVM
    {
        public string Title { get; set; }
        public string Image { get; set; }
    }
}

MVCPractice2/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;


namespace MVCPractice2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MVCPractice2/ViewComponents/BannerViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class BannerViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MVCPractice2/ViewComponents/BestSalerViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class BestSalerViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }

    }
}

MVCPractice2/ViewComponents/FactViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class FactViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MVCPractice2/ViewComponents/FeatureSectionViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class FeatureSectionViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MVCPractice2/ViewComponents/FeatureViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class FeatureViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MVCPractice2/ViewComponents/FruitViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class FruitViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MVCPractice2/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCPractice2.Services.Interfaces;

namespace MVCPractice2.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        private readonly ILayoutService _layoutService;
        public HeaderViewComponent(ILayoutService layoutService)
        {
            _layoutService = layoutService; 
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var settings = await _layoutService.GetAllSettingsAsync();
            return View(settings);
        }
    }
}

MVCPractice2/ViewComponents/HeroViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using MVCPractice2.Services.Interfaces;
using MVCPractice2.ViewModels.Slider;

namespace MVCPractice2.ViewComponents
{
    public class HeroViewComponent : ViewComponent
    {
        private readonly ISliderInfoService _sliderInfoService;
        private readonly ISliderService _sliderService;

        public HeroViewComponent(ISliderService sliderService, ISliderInfoService sliderInfoService)
        {
            _sliderService = sliderService;
            _sliderInfoService = sliderInfoService;

        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var sliderInfos = await _sliderInfoService.GetAllAsync();
            var sliders = await _sliderService.GetAllAsync();

            SliderVMVC model = new SliderVMVC()
            {
                SliderInfo = sliderInfos,
                Sliders = sliders
            };

            return View(model);
        }
    }

    public class SliderVMVC
    {
        public SliderInfoUIVM SliderInfo { get; set; }
        public IEnumerable<SliderUIVM> Sliders { get; set; }

    }
}

MVCPractice2/ViewComponents/TastimonialViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class TastimonialViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MVCPractice2/ViewComponents/VesitableViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCPractice2.ViewComponents
{
    public class VesitableViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return View();
        }
    }
}

MVCPractice2/Views/Home/Index.cshtml
@await Component.InvokeAsync("Hero")
@await Component.InvokeAsync("Feature")
@await Component.InvokeAsync("Fruit")
@await Component.InvokeAsync("FeatureSection")
@await Component.InvokeAsync("Vesitable")
@await Component.InvokeAsync("Banner")

@await Component.InvokeAsync("BestSaler")

@await Component.InvokeAsync("Fact")
@await Component.InvokeAsync("Tastimonial")

MVCPractice2/Views/Shared/Components/Banner/Default.cshtml
<!-- Banner Section Start-->
<div class="container-fluid banner bg-secondary my-5">
    <div class="container py-5">
        <div class="row g-4 align-items-center">
            <div class="col-lg-6">
                <div class="py-4">
                    <h1 class="display-3 text-white">Fresh Exotic Fruits</h1>
                    <p class="fw-normal display-3 text-dark mb-4">in Our Store</p>
                    <p class="mb-4 text-dark">
                        The generated Lorem Ipsum is therefore always free from
                        repetition injected humour, or non-characteristic words etc.
                    </p>
                    <a href="#"
                       class="banner-btn btn border-2 border-white rounded-pill text-dark py-3 px-5">BUY</a>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="position-relative">
                    <img src="~/assets/img/baner-1.png"
                         class="img-fluid w-100 rounded"
                         alt="" />
                    <div class="d-flex align-items-center justify-content-center bg-white rounded-circle position-absolute"
                         style="width: 140px; height: 140px; top: 0; left: 0">
                        <h1 style="font-size: 100px">1</h1>
                        <div class="d-flex flex-column">
                            <span class="h2 mb-0">50$</span>
                            <span class="h4 text-muted mb-0">kg</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Section End -->

MVCPractice2/Views/Shared/Components/BestSaler/Default.cshtml
<!-- Bestsaler Product Start -->
<div class="container-fluid py-5">
    <div class="container py-5">
        <div class="text-center mx-auto mb-5" style="max-width: 700px">
            <h1 class="display-4">Bestseller Products</h1>
            <p>
                Latin words, combined with a handful of model sentence structures,
                to generate Lorem Ipsum which looks reasonable.
            </p>
        </div>
        <div class="row g-4">
            <div class="col-lg-6 col-xl-4">
                <div class="p-4 rounded bg-light">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <img src="~/assets/img/best-product-1.jpg"
                                 class="img-fluid rounded-circle w-100"
                                 alt="" />
                        </div>
                        <div class="col-6">
                            <a href="#" class="h5">Organic Tomato</a>
                            <div class="d-flex my-3">
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h4 class="mb-3">3.12 $</h4>
                            <a href="#"
                               class="btn border border-secondary rounded-pill px-3 text-primary">
                                <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                                cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-4">
                <div class="p-4 rounded bg-light">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <img src="~/assets/img/best-product-2.jpg"
                                 class="img-fluid rounded-circle w-100"
                                 alt="" />
                        </div>
                        <div class="col-6">
                            <a href="#" class="h5">Organic Tomato</a>
                            <div class="d-flex my-3">
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h4 class="mb-3">3.12 $</h4>
                            <a href="#"
                               class="btn border border-secondary rounded-pill px-3 text-primary">
                                <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                                cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-4">
                <div class="p-4 rounded bg-light">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <img src="~/assets/img/best-product-3.jpg"
                                 class="img-fluid rounded-circle w-100"
                                 alt="" />
                        </div>
                        <div class="col-6">
                            <a href="#" class="h5">Organic Tomato</a>
                            <div class="d-flex my-3">
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h4 class="mb-3">3.12 $</h4>
                            <a href="#"
                               class="btn border border-secondary rounded-pill px-3 text-primary">
                                <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                                cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-4">
                <div class="p-4 rounded bg-light">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <img src="~/assets/img/best-product-4.jpg"
                                 class="img-fluid rounded-circle w-100"
                                 alt="" />
                        </div>
                        <div class="col-6">
                            <a href="#" class="h5">Organic Tomato</a>
                            <div class="d-flex my-3">
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h4 class="mb-3">3.12 $</h4>
                            <a href="#"
                               class="btn border border-secondary rounded-pill px-3 text-primary">
                                <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                                cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-4">
                <div class="p-4 rounded bg-light">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <img src="~/assets/img/best-product-5.jpg"
                                 class="img-fluid rounded-circle w-100"
                                 alt="" />
                        </div>
                        <div class="col-6">
                            <a href="#" class="h5">Organic Tomato</a>
                            <div class="d-flex my-3">
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h4 class="mb-3">3.12 $</h4>
                            <a href="#"
                               class="btn border border-secondary rounded-pill px-3 text-primary">
                                <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                                cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-xl-4">
                <div class="p-4 rounded bg-light">
                    <div class="row align-items-center">
                        <div class="col-6">
                            <img src="~/assets/img/best-product-6.jpg"
                                 class="img-fluid rounded-circle w-100"
                                 alt="" />
                        </div>
                        <div class="col-6">
                            <a href="#" class="h5">Organic Tomato</a>
                            <div class="d-flex my-3">
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star text-primary"></i>
                                <i class="fas fa-star"></i>
                            </div>
                            <h4 class="mb-3">3.12 $</h4>
                            <a href="#"
                               class="btn border border-secondary rounded-pill px-3 text-primary">
                                <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                                cart
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="text-center">
                    <img src="~/assets/img/fruite-item-1.jpg"
                         class="img-fluid rounded"
                         alt="" />
                    <div class="py-4">
                        <a href="#" class="h5">Organic Tomato</a>
                        <div class="d-flex my-3 justify-content-center">
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        <h4 class="mb-3">3.12 $</h4>
                        <a href="#"
                           class="btn border border-secondary rounded-pill px-3 text-primary">
                            <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                            cart
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="text-center">
                    <img src="~/assets/img/fruite-item-2.jpg"
                         class="img-fluid rounded"
                         alt="" />
                    <div class="py-4">
                        <a href="#" class="h5">Organic Tomato</a>
                        <div class="d-flex my-3 justify-content-center">
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        <h4 class="mb-3">3.12 $</h4>
                        <a href="#"
                           class="btn border border-secondary rounded-pill px-3 text-primary">
                            <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                            cart
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="text-center">
                    <img src="~/assets/img/fruite-item-3.jpg"
                         class="img-fluid rounded"
                         alt="" />
                    <div class="py-4">
                        <a href="#" class="h5">Organic Tomato</a>
                        <div class="d-flex my-3 justify-content-center">
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        <h4 class="mb-3">3.12 $</h4>
                        <a href="#"
                           class="btn border border-secondary rounded-pill px-3 text-primary">
                            <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                            cart
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-6 col-xl-3">
                <div class="text-center">
                    <img src="~/assets/img/fruite-item-4.jpg"
                         class="img-fluid rounded"
                         alt="" />
                    <div class="py-2">
                        <a href="#" class="h5">Organic Tomato</a>
                        <div class="d-flex my-3 justify-content-center">
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star text-primary"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        <h4 class="mb-3">3.12 $</h4>
                        <a href="#"
                           class="btn border border-secondary rounded-pill px-3 text-primary">
                            <i class="fa fa-shopping-bag me-2 text-primary"></i> Add to
                            cart
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Bestsaler Product End -->

MVCPractice2/Views/Shared/Components/Fact/Default.cshtml
<!-- Fact Start -->
<div class="container-fluid py-5">
    <div class="container">
        <div class="bg-light p-5 rounded">
            <div class="row g-4 justify-content-center">
                <div class="col-md-6 col-lg-6 col-xl-3">
                    <div class="counter bg-white rounded p-5">
                        <i class="fa fa-users text-secondary"></i>
                        <h4>satisfied customers</h4>
                        <h1>1963</h1>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-3">
                    <div class="counter bg-white rounded p-5">
                        <i class="fa fa-users text-secondary"></i>
                        <h4>quality of service</h4>
                        <h1>99%</h1>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-3">
                    <div class="counter bg-white rounded p-5">
                        <i class="fa fa-users text-secondary"></i>
                        <h4>quality certificates</h4>
                        <h1>33</h1>
                    </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-3">
                    <div class="counter bg-white rounded p-5">
                        <i class="fa fa-users text-secondary"></i>
                        <h4>Available Products</h4>
                        <h1>789</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Fact Start -->

MVCPractice2/Views/Shared/Components/Feature/Default.cshtml
<!-- Featurs Section Start -->
<div class="container-fluid featurs py-5">
    <div class="container py-5">
        <div class="row g-4">
            <div class="col-md-6 col-lg-3">
                <div class="featurs-item text-center rounded bg-light p-4">
                    <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                        <i class="fas fa-car-side fa-3x text-white"></i>
                    </div>
                    <div class="featurs-content text-center">
                        <h5>Free Shipping</h5>
                        <p class="mb-0">Free on order over $300</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="featurs-item text-center rounded bg-light p-4">
                    <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                        <i class="fas fa-user-shield fa-3x text-white"></i>
                    </div>
                    <div class="featurs-content text-center">
                        <h5>Security Payment</h5>
                        <p class="mb-0">100% security payment</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="featurs-item text-center rounded bg-light p-4">
                    <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                        <i class="fas fa-exchange-alt fa-3x text-white"></i>
                    </div>
                    <div class="featurs-content text-center">
                        <h5>30 Day Return</h5>
                        <p class="mb-0">30 day money guarantee</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-lg-3">
                <div class="featurs-item text-center rounded bg-light p-4">
                    <div class="featurs-icon btn-square rounded-circle bg-secondary mb-5 mx-auto">
                        <i class="fa fa-phone-alt fa-3x text-white"></i>
                    </div>
                    <div class="featurs-content text-center">
                        <h5>24/7 Support</h5>
                        <p class="mb-0">Support every time fast</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Featurs Section End -->

MVCPractice2/Views/Shared/Components/FeatureSection/Default.cshtml
<!-- Featurs Start -->
<div class="container-fluid service py-5">
    <div class="container py-5">
        <div class="row g-4 justify-content-center">
            <div class="col-md-6 col-lg-4">
                <a href="#">
                    <div class="service-item bg-secondary rounded border border-secondary">
                        <img src="~/assets/img/featur-1.jpg"
                             class="img-fluid rounded-top w-100"
                             alt="" />
                        <div class="px-4 rounded-bottom">
                            <div class="service-content bg-primary text-center p-4 rounded">
                                <h5 class="text-white">Fresh Apples</h5>
                                <h3 class="mb-0">20% OFF</h3>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a href="#">
                    <div class="service-item bg-dark rounded border border-dark">
                        <img src="~/assets/img/featur-2.jpg"
                             class="img-fluid rounded-top w-100"
                             alt="" />
                        <div class="px-4 rounded-bottom">
                            <div class="service-content bg-light text-center p-4 rounded">
                                <h5 class="text-primary">Tasty Fruits</h5>
                                <h3 class="mb-0">Free delivery</h3>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-6 col-lg-4">
                <a href="#">
                    <div class="service-item bg-primary rounded border border-primary">
                        <img src="~/assets/img/featur-3.jpg"
                             class="img-fluid rounded-top w-100"
                             alt="" />
                        <div class="px-4 rounded-bottom">
                            <div class="service-content bg-secondary text-center p-4 rounded">
                                <h5 class="text-white">Exotic Vegitable</h5>
                                <h3 class="mb-0">Discount 30$</h3>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Featurs End -->

MVCPractice2/Views/Shared/Components/Hero/Default.cshtml
@model SliderVMVC

<!-- Hero Start -->
<div class="container-fluid py-5 mb-5 hero-header">
    <div class="container py-5">
        <div class="row g-5 align-items-center">
            <div class="col-md-12 col-lg-7">
                <h4 class="mb-3 text-secondary">@Model.SliderInfo.Title</h4>
                <h1 class="mb-5 display-3 text-primary">
                    @Model.SliderInfo.Description
                </h1>
                <div class="position-relative mx-auto">
                    <input class="form-control border-2 border-secondary w-75 py-3 px-4 rounded-pill"
                    type="number"
                    placeholder="Search" />
                    <button type="submit"
                    class="btn btn-primary border-2 border-secondary py-3 px-4 position-absolute rounded-pill text-white h-100"
                    style="top: 0; right: 25%">
                        Submit Now
                    </button>
                </div>
            </div>
            <div class="col-md-12 col-lg-5">
                <div id="carouselId"
                class="carousel slide position-relative"
                data-bs-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                        @foreach (var item in Model.Sliders)
                        {
                            <div class="carousel-item active rounded">
                                <img src="~/assets/img/@item.Image"
                                     class="img-fluid w-100 h-100 bg-secondary rounded"
                                     alt="First slide" />
                                <a href="#" class="btn px-4 py-2 text-white rounded">@item.Title</a>
                            </div>
                        } 

                    </div>
                    <button class="carousel-control-prev"
                            type="button"
                            data-bs-target="#carouselId"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon"
                              aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next"
                            type="button"
                            data-bs-target="#carouselId"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon"
                              aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Hero End -->